// Забороняємо горизонтальне перетягування сторінки на мобільних пристроях
const layoutLockStyle=document.createElement('style');layoutLockStyle.textContent=`
html,body{width:100%;max-width:100%;overflow-x:hidden!important;overscroll-behavior-x:none;touch-action:pan-y pinch-zoom}
body{position:relative}
.hp-crypto{width:100%;max-width:100%;overflow-x:clip}
img,video,iframe,svg{max-width:100%}
*{box-sizing:border-box}
@supports(overflow:clip){html,body{overflow-x:clip!important}}
`;document.head.appendChild(layoutLockStyle);

const countdownElement=document.getElementById('countdown');
const countdownDate=new Date('2026-07-30T23:59:59').getTime();
function updateCountdown(){if(!countdownElement)return;const d=countdownDate-Date.now();if(d<=0){countdownElement.textContent='Акцію завершено';return;}const days=Math.floor(d/86400000),hours=Math.floor(d%86400000/3600000),minutes=Math.floor(d%3600000/60000),seconds=Math.floor(d%60000/1000);countdownElement.textContent=`${days}д ${hours}г ${minutes}хв ${seconds}с`;}
updateCountdown();setInterval(updateCountdown,1000);

// Мобільне меню та плавна прокрутка
(()=>{const burger=document.getElementById('hpBurger'),nav=document.getElementById('hpMobileNav'),close=document.getElementById('hpMobileClose');burger?.addEventListener('click',()=>nav?.classList.add('active'));close?.addEventListener('click',()=>nav?.classList.remove('active'));document.querySelectorAll('.hp-mnav-link').forEach(a=>a.addEventListener('click',()=>nav?.classList.remove('active')));document.querySelectorAll('.hp-crypto a[href^="#"]').forEach(a=>a.addEventListener('click',function(e){const href=this.getAttribute('href');if(!href||href==='#'||href.includes('order'))return;const target=document.querySelector(href);if(!target)return;e.preventDefault();window.scrollTo({top:target.getBoundingClientRect().top+scrollY-80,behavior:'smooth'});}));})();

// Кастомний курсор
const cursor=document.getElementById('cursor');let lastTrail=0;
function createTrail(x,y){const now=performance.now();if(now-lastTrail<25)return;lastTrail=now;const t=document.createElement('div');t.className='trail';t.style.left=x+'px';t.style.top=y+'px';document.body.appendChild(t);setTimeout(()=>t.remove(),500);}
if(cursor&&matchMedia('(pointer: fine)').matches){document.addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';createTrail(e.clientX,e.clientY);});document.querySelectorAll('button,a').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.style.width='60px';cursor.style.height='60px';});el.addEventListener('mouseleave',()=>{cursor.style.width='28px';cursor.style.height='28px';});});document.addEventListener('mousedown',()=>cursor.style.transform='translate(-50%,-50%) scale(.75)');document.addEventListener('mouseup',()=>cursor.style.transform='translate(-50%,-50%) scale(1)');}

// Форма заявки
const modal=document.getElementById('registerModal'),closeModalButton=document.getElementById('closeModal'),form=document.getElementById('registerForm'),formContent=document.getElementById('formContent'),successMessage=document.getElementById('successMessage');
function openRegisterModal(e){e?.preventDefault();modal?.classList.add('active');}
function closeRegisterModal(){modal?.classList.remove('active');}
document.querySelectorAll('#openModal,.openModal').forEach(b=>b.addEventListener('click',openRegisterModal));closeModalButton?.addEventListener('click',closeRegisterModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeRegisterModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeRegisterModal();});
const GOOGLE_FORM_URL='https://docs.google.com/forms/d/e/1FAIpQLSd6Ks1Sm09cZwJd6BsEXn9Ca7avQWwnom9d8iN2B5sITO8dYQ/formResponse';
form?.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('.submit-btn'),contact=document.querySelector('input[name="contact"]:checked');if(!btn||!contact)return;btn.disabled=true;btn.textContent='Відправляємо...';const data=new FormData();data.append('entry.1507431541',document.getElementById('userName')?.value.trim()||'');data.append('entry.526374724',document.getElementById('userPhone')?.value.trim()||'');data.append('entry.1622305066',contact.value);try{await fetch(GOOGLE_FORM_URL,{method:'POST',mode:'no-cors',body:data});form.reset();if(formContent)formContent.style.display='none';successMessage?.classList.add('active');setTimeout(()=>{successMessage?.classList.remove('active');if(formContent)formContent.style.display='block';closeRegisterModal();},3000);}catch(err){alert('❌ Не вдалося відправити заявку. Спробуйте ще раз.');console.error(err);}finally{btn.disabled=false;btn.textContent='Записатися';}});

// Загальне модальне вікно для інформації
const infoStyle=document.createElement('style');infoStyle.textContent=`
.info-overlay{position:fixed;inset:0;z-index:10050;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(0,0,0,.82);backdrop-filter:blur(8px);opacity:0;visibility:hidden;transition:.24s}.info-overlay.active{opacity:1;visibility:visible}.info-window{position:relative;width:min(620px,100%);max-height:86vh;overflow:auto;padding:34px 30px;border:1px solid rgba(0,225,95,.5);border-radius:22px;background:linear-gradient(145deg,#08130d,#030806);box-shadow:0 0 60px rgba(0,220,90,.18);transform:scale(.95);transition:.24s}.info-overlay.active .info-window{transform:scale(1)}.info-close{position:absolute;right:15px;top:13px;width:40px;height:40px;border:1px solid rgba(0,225,95,.35);border-radius:50%;background:#07100a;color:#fff;font-size:24px;cursor:pointer}.info-label{color:#00df65;font-size:13px;font-weight:800;letter-spacing:.13em}.info-title{margin:10px 45px 14px 0;color:#fff;font-size:clamp(26px,6vw,36px)}.info-desc{color:#aeb8b2;font-size:17px;line-height:1.65}.info-list{list-style:none;padding:0;margin:18px 0 0}.info-list li{position:relative;padding:10px 0 10px 29px;color:#eef3f0;border-bottom:1px solid rgba(255,255,255,.06);line-height:1.45}.info-list li:before{content:'✓';position:absolute;left:0;color:#00e86b;font-weight:900}body.info-open{overflow:hidden}
.hp-crypto__cards .hp-crypto__card{cursor:pointer;transition:.25s}.hp-crypto__cards .hp-crypto__card:hover{transform:translateY(-5px);border-color:#00dc61;box-shadow:0 14px 36px rgba(0,220,90,.14)}.hp-crypto__cards .hp-crypto__card:after{content:'Натисни, щоб дізнатися більше';display:block;margin-top:14px;color:#00d95f;font-size:12px;font-weight:700}
.course-modules{max-width:1180px;margin:65px auto 90px;padding:0 20px}.course-modules__eyebrow{text-align:center;color:#00d75f;font-size:14px;letter-spacing:3px;text-transform:uppercase;margin-bottom:12px}.course-modules__title{text-align:center;color:#fff;font-size:clamp(34px,5vw,62px);line-height:1.05;margin:0;font-family:Georgia,serif;text-transform:uppercase}.course-modules__subtitle{text-align:center;color:#89928d;font-size:18px;margin:18px auto 40px;max-width:650px}.course-modules__grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.module-card{position:relative;min-height:265px;padding:27px 23px;border:1px solid rgba(0,215,95,.28);border-radius:23px;background:linear-gradient(145deg,rgba(7,20,12,.97),rgba(2,10,6,.99));cursor:pointer;overflow:hidden;transition:.3s;color:#fff;text-align:left}.module-card:hover,.module-card:focus{transform:translateY(-6px);border-color:#00d75f;box-shadow:0 16px 45px rgba(0,215,95,.16);outline:none}.module-number{font-size:52px;font-weight:900;color:rgba(0,215,95,.22);line-height:1}.module-duration{display:inline-block;margin-top:20px;padding:7px 12px;border-radius:99px;background:rgba(0,215,95,.12);color:#00e86b;font-size:13px;font-weight:800}.module-card h3{font-size:22px;margin:17px 0 9px;color:#fff}.module-card p{margin:0;color:#87908b;line-height:1.5}.module-more{position:absolute;right:20px;bottom:17px;color:#00e86b;font-size:20px}@media(max-width:900px){.course-modules__grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.course-modules{margin:55px auto 70px;padding:0 14px}.course-modules__grid{grid-template-columns:1fr 1fr;gap:11px}.module-card{min-height:230px;padding:19px 15px;border-radius:17px}.module-number{font-size:39px}.module-card h3{font-size:17px}.module-card p{font-size:13px}.course-modules__subtitle{font-size:16px}.info-window{padding:29px 21px}.info-desc{font-size:16px}}
`;document.head.appendChild(infoStyle);
const overlay=document.createElement('div');overlay.className='info-overlay';overlay.innerHTML=`<div class="info-window" role="dialog" aria-modal="true"><button class="info-close" aria-label="Закрити">×</button><div class="info-label"></div><h3 class="info-title"></h3><p class="info-desc"></p><ul class="info-list"></ul></div>`;document.body.appendChild(overlay);
function showInfo(label,title,desc,items=[]){overlay.querySelector('.info-label').textContent=label;overlay.querySelector('.info-title').textContent=title;overlay.querySelector('.info-desc').textContent=desc;const ul=overlay.querySelector('.info-list');ul.innerHTML=items.map(i=>`<li>${i}</li>`).join('');ul.style.display=items.length?'block':'none';overlay.classList.add('active');document.body.classList.add('info-open');}
function hideInfo(){overlay.classList.remove('active');document.body.classList.remove('info-open');}
overlay.querySelector('.info-close').addEventListener('click',hideInfo);overlay.addEventListener('click',e=>{if(e.target===overlay)hideInfo();});document.addEventListener('keydown',e=>{if(e.key==='Escape')hideInfo();});

// Чотири верхні картки
const cardInfo=[['Smart Money','Smart Money — це аналіз ринку через дії великих учасників. Ти навчишся бачити зони ліквідності, маніпуляції та місця, звідки може початися сильний рух ціни.'],['Аналіз ліквідності','Ліквідність — це зони накопичення ордерів і стоп-лосів. Їхній пошук допомагає розуміти можливі цілі ціни та уникати входів у момент маніпуляції.'],['Пошук точок входу','Якісна точка входу з’являється після підтвердження структури. Ти отримаєш алгоритм входу з логічним стоп-лосом і визначеною ціллю.'],['Управління капіталом','Ризик-менеджмент допомагає захистити депозит, контролювати втрати та зберігати стабільність на довгій дистанції.']];
document.querySelectorAll('.hp-crypto__cards .hp-crypto__card').forEach((card,i)=>{card.tabIndex=0;const open=()=>showInfo('ЩО ЦЕ ТАКЕ?',cardInfo[i][0],cardInfo[i][1]);card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});});

// Чотири модулі навчання
(()=>{const faq=Array.from(document.querySelectorAll('details'))[0]?.parentElement;if(!faq||document.getElementById('courseModules'))return;const modules=[
{n:'01',title:'Основи криптовалюти',duration:'2 дні',desc:'Теорія та практика роботи з криптовалютною інфраструктурою.',items:['Робота з криптовалютними біржами','Реєстрація та базове налаштування акаунтів','Гарячі та холодні гаманці','Безпечне зберігання активів','Поповнення рахунку та виведення коштів','Практичне виконання основних операцій']},
{n:'02',title:'Інструменти трейдера',duration:'2 дні',desc:'Готуємо повноцінне робоче місце для аналізу та торгівлі.',items:['Завантаження всіх необхідних програм','Налаштування TradingView та допоміжних сервісів','Робота з CoinMarketCap і Coinglass','Налаштування біржі та Telegram','Практика з кожним інструментом','Подарунки й матеріали для успішного старту']},
{n:'03',title:'Smart Money',duration:'4 дні',desc:'Поглиблене навчання аналізу ринку за концепцією Smart Money.',items:['Структура ринку','BOS і CHoCH','Ліквідність та маніпуляції','Order Blocks і Fair Value Gaps','Пошук якісних точок входу','Максимум теорії та практика на реальних графіках']},
{n:'04',title:'Трейдинг як професія',duration:'Практика',desc:'Переходимо від навчання до системної самостійної торгівлі.',items:['Разом шукаємо торгові позиції','Проводимо повний аналіз перед входом','Входимо в угоди за чітким алгоритмом','Встановлюємо Stop Loss і Take Profit','Працюємо з ризик-менеджментом','Формуємо торговий план і професійний підхід']}
];const section=document.createElement('section');section.className='course-modules';section.id='courseModules';section.innerHTML=`<div class="course-modules__eyebrow">Повна програма</div><h2 class="course-modules__title">Що буде на навчанні</h2><p class="course-modules__subtitle">4 модулі — від перших кроків у крипті до системної торгівлі</p><div class="course-modules__grid">${modules.map((m,i)=>`<button class="module-card" type="button" data-i="${i}"><div class="module-number">${m.n}</div><span class="module-duration">${m.duration}</span><h3>${m.title}</h3><p>${m.desc}</p><span class="module-more">↗</span></button>`).join('')}</div>`;faq.insertAdjacentElement('afterend',section);section.querySelectorAll('.module-card').forEach(card=>card.addEventListener('click',()=>{const m=modules[+card.dataset.i];showInfo(`МОДУЛЬ ${m.n} • ${m.duration}`,m.title,m.desc,m.items);}));})();

// Яскраві падаючі зірки та криптомонети на фоні, у тому числі на мобільних
(()=>{const style=document.createElement('style');style.textContent=`
.crypto-rain-layer{position:fixed;inset:0;z-index:2;pointer-events:none;overflow:hidden}.hp-crypto{position:relative;z-index:1}.crypto-fall{position:absolute;top:-120px;left:var(--start);width:var(--size);height:var(--size);display:grid;place-items:center;border:1px solid rgba(80,255,155,.62);border-radius:50%;color:rgba(125,255,180,.9);background:radial-gradient(circle,rgba(0,255,125,.32),rgba(0,0,0,.03) 72%);box-shadow:0 0 24px rgba(0,255,125,.38),0 0 48px rgba(0,220,90,.2);font:800 calc(var(--size)*.5)/1 Arial,sans-serif;opacity:0;filter:drop-shadow(0 0 8px rgba(80,255,155,.65));animation:cryptoMeteor var(--duration) linear forwards;will-change:transform,opacity}.crypto-fall:after{content:'';position:absolute;width:150px;height:2px;right:68%;top:50%;background:linear-gradient(90deg,transparent,rgba(100,255,175,.72));transform:rotate(-28deg);transform-origin:right center;box-shadow:0 0 10px rgba(80,255,155,.45)}@keyframes cryptoMeteor{0%{transform:translate3d(0,-14vh,0) rotate(0deg) scale(.72);opacity:0}8%{opacity:var(--opacity)}86%{opacity:var(--opacity)}100%{transform:translate3d(var(--drift),118vh,0) rotate(540deg) scale(1.05);opacity:0}}@media(max-width:600px){.crypto-rain-layer{z-index:3}.crypto-fall{border-color:rgba(110,255,180,.78);color:rgba(165,255,205,.98);background:radial-gradient(circle,rgba(0,255,135,.46),rgba(0,0,0,.02) 74%);box-shadow:0 0 26px rgba(0,255,135,.5),0 0 55px rgba(0,220,90,.28);filter:drop-shadow(0 0 10px rgba(110,255,180,.82))}.crypto-fall:after{width:120px;height:2px;background:linear-gradient(90deg,transparent,rgba(140,255,200,.88))}}
`;document.head.appendChild(style);const layer=document.createElement('div');layer.className='crypto-rain-layer';layer.setAttribute('aria-hidden','true');document.body.appendChild(layer);const mobile=matchMedia('(max-width:600px)').matches;const symbols=['★','✦','✧','₿','Ξ','◎'];const maxCount=mobile?8:6;function spawnCoin(){if(layer.childElementCount>=maxCount)return;const coin=document.createElement('span');coin.className='crypto-fall';coin.textContent=symbols[Math.floor(Math.random()*symbols.length)];coin.style.setProperty('--start',`${2+Math.random()*94}%`);coin.style.setProperty('--size',`${mobile?20+Math.random()*22:26+Math.random()*25}px`);coin.style.setProperty('--duration',`${mobile?5.8+Math.random()*3.2:7+Math.random()*4}s`);coin.style.setProperty('--drift',`${-130+Math.random()*260}px`);coin.style.setProperty('--opacity',`${mobile?.72+Math.random()*.24:.46+Math.random()*.28}`);layer.appendChild(coin);coin.addEventListener('animationend',()=>coin.remove(),{once:true});}for(let i=0;i<(mobile?4:2);i++)setTimeout(spawnCoin,i*350);setInterval(spawnCoin,mobile?1200:2200);})();

// Компактний віджет зв'язку з менеджером: розмір як у кнопки «вгору», показ після 500 px прокрутки
(()=>{if(document.getElementById('managerChatWidget'))return;const style=document.createElement('style');style.textContent=`
.manager-chat{position:fixed;right:20px;bottom:78px;z-index:9995;display:flex;flex-direction:column;align-items:flex-end;gap:8px;font-family:Arial,sans-serif;opacity:0;visibility:hidden;transform:translateY(10px);pointer-events:none;transition:opacity .22s,transform .22s,visibility .22s}.manager-chat.visible{opacity:1;visibility:visible;transform:none;pointer-events:auto}.manager-chat__panel{position:relative;width:min(290px,calc(100vw - 30px));padding:17px 16px 15px;border:1px solid rgba(0,230,100,.5);border-radius:16px;background:linear-gradient(145deg,rgba(7,18,11,.98),rgba(2,8,5,.98));box-shadow:0 18px 55px rgba(0,0,0,.45),0 0 28px rgba(0,220,90,.13);transform:translateY(10px) scale(.96);transform-origin:bottom right;opacity:0;visibility:hidden;transition:.22s}.manager-chat.open .manager-chat__panel{transform:none;opacity:1;visibility:visible}.manager-chat__close{position:absolute;top:8px;right:10px;border:0;background:transparent;color:#829087;font-size:21px;line-height:1;cursor:pointer}.manager-chat__title{margin:0 30px 7px 0;color:#fff;font-size:18px}.manager-chat__text{margin:0 0 13px;color:#a6b0aa;font-size:14px;line-height:1.45}.manager-chat__link{display:flex;align-items:center;justify-content:center;gap:8px;width:100%;padding:10px 13px;border-radius:10px;background:#16d866;color:#021307!important;text-decoration:none;font-size:14px;font-weight:800;box-shadow:0 0 22px rgba(22,216,102,.22)}.manager-chat__button{position:relative;width:40px;height:40px;padding:0;display:grid;place-items:center;border:1px solid rgba(0,235,105,.65);border-radius:50%;background:linear-gradient(145deg,#0c2817,#06130b);color:#1cff78;box-shadow:0 6px 18px rgba(0,0,0,.3),0 0 14px rgba(0,225,90,.15);cursor:pointer;transition:.2s}.manager-chat__button:hover{transform:scale(1.04)}.manager-chat__button svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.8}.manager-chat__dot{position:absolute;right:0;top:0;width:8px;height:8px;border:2px solid #07110b;border-radius:50%;background:#ff4d4d}@media(max-width:600px){.manager-chat{right:14px;bottom:72px}.manager-chat__button{width:40px;height:40px}.manager-chat__button svg{width:18px;height:18px}}
`;document.head.appendChild(style);const widget=document.createElement('div');widget.className='manager-chat';widget.id='managerChatWidget';widget.innerHTML=`<div class="manager-chat__panel" role="dialog" aria-label="Зв'язок з менеджером"><button class="manager-chat__close" type="button" aria-label="Закрити">×</button><h3 class="manager-chat__title">Є питання?</h3><p class="manager-chat__text">Можете поставити їх менеджеру — він допоможе та підкаже деталі навчання.</p><a class="manager-chat__link" href="https://t.me/Levkoyss" target="_blank" rel="noopener">Написати в Telegram</a></div><button class="manager-chat__button" type="button" aria-label="Написати менеджеру" aria-expanded="false"><span class="manager-chat__dot"></span><svg viewBox="0 0 24 24"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"></path><path d="M8 9h8M8 13h5"></path></svg></button>`;document.body.appendChild(widget);const button=widget.querySelector('.manager-chat__button'),close=widget.querySelector('.manager-chat__close'),dot=widget.querySelector('.manager-chat__dot');function openWidget(){widget.classList.add('open');button.setAttribute('aria-expanded','true');dot.style.display='none';}function closeWidget(){widget.classList.remove('open');button.setAttribute('aria-expanded','false');}function updateVisibility(){const visible=window.scrollY>=500;widget.classList.toggle('visible',visible);if(!visible)closeWidget();}button.addEventListener('click',()=>widget.classList.contains('open')?closeWidget():openWidget());close.addEventListener('click',closeWidget);window.addEventListener('scroll',updateVisibility,{passive:true});updateVisibility();})();